// import 'bootstrap/dist/css/bootstrap.css';
import "@styles/globals.css";
import Script from "next/script";

export const metadata = {
  title: "Conventional AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="preconnect"
          href="https://fonts.googleapis.com"
        />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Tilt+Prism&display=swap"
          rel="stylesheet"
        />
      </head>

      <body>
        <main>{children}</main>
      </body>
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"/>
    </html>
  );
}
