import "@styles/globals.css";
import { Toast } from "../components/toast/index";
import UserContextProvider from "@context/UserContextProvider";
import ProjectContextProvider from "@context/ProjectContextProvider";

export const metadata = {
  title: "Conventional AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="preconnect"
          href="https://fonts.googleapis.com"
        />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Tilt+Prism&display=swap"
          rel="stylesheet"
        />
      </head>

      <body>
        <main>
          <UserContextProvider>
            <ProjectContextProvider>
              <Toast />
              {children}
            </ProjectContextProvider>
          </UserContextProvider>
        </main>
      </body>
    </html>
  );
}
